Repository wrappid/core, pull requests merged in 2024-02, with the labels that each got.

#94 docs: :memo: correct details in the table
  ATTRIBUTIONS.md
  scripts/attributions.gen.js
Labels: documentation

#95 fix(core): :bug: import the missing component CoreRoutesContext
  package/index.js
Labels: bug

#99 Merge development into main
  ATTRIBUTIONS.md
  package/index.js
  scripts/attributions.gen.js
Labels: enhancement

#104 fix: :bug: uncommented openCollapse
  package/utils/menuUtil.js
Labels: bug

#111 refactor: styles file export consistency
  .gitignore
  package-lock.json
  package.json
  package/index.js
  package/package-lock.json
  package/store/CoreProvider.js
  package/styles/DefaultCoreStyles.js
  package/styles/LargeCoreStyles.js
  package/styles/MediumCoreStyles.js
  package/styles/SmallCoreStyles.js
  package/styles/XLargeCoreStyles.js
  package/styles/XXLargeCoreStyles.js
Labels: cleanup

#105 fix(core): :bug: add missing styleClasses props in CoreTypographyBody…
  package/components/dataDisplay/CoreTypographyBody2.js
Labels: bug

#122 fix: :bug: gutterBottom default value changed to false.
  package/components/dataDisplay/CoreTypography.js
  package/components/dataDisplay/CoreTypographyBody2.js
Labels: bug

#124 merge: from Development
  CHANGELOG.md
  package/index.js
  package/theme/ThemeSelector.js
Labels: bug

#136 theme related fixes
  package/theme/CoreThemeProvider.js
  package/theme/ThemeSelector.js
Labels: enhancement

#138 fix: :bug: left menu openCollapse not working issue resolved
  package/components/surfaces/CoreDrawer.js
  package/utils/menuUtil.js
Labels: bug

#144 feat: :sparkles: OnlineStatusSnackbar component implementation
  package/components/feedback/CoreSnackbar.js
  package/components/utils/OnlineStatus.js
  package/components/utils/OnlineStatusSnackbar.js
  package/index.js
Labels: enhancement

#145 enhancement: layout manager working
  package/components/WrappidComponent.js
  package/development/DevelopmentInfo.js
  package/layout/BlankLayout.js
  package/layout/PageContainer.js
  package/layout/WrappidDefault.layout.js
  package/layout/core/LayoutManager.js
  package/layout/page/BlankLayoutPage.js
  package/layout/page/FixedHeaderFooterLayoutPage.js
  package/layout/page/FixedHeaderLayoutPage.js
Labels: enhancement

#150 route and layout related issue resolved
  package/CoreRoutes.js
  package/development/DevelopmentInfo.js
  package/layout/PageContainer.js
  package/layout/core/CoreLayoutPlaceholder.js
  package/layout/core/LayoutManager.js
  package/registry/ComponentsRegistry.js
  package/registry/LayoutComponentsRegistry.js
  package/utils/jsonUtils.js
Labels: bug

#154 enhancement: pr guardrails and package.json dependencies.
  .github/workflows/pr-guardrails.yml
  package-lock.json
  package.json
Labels: enhancement, dependencies

#155 enhancement: created OnlineStatusSnackbar component and used in PageContainer
  package/components/utils/OnlineStatusSnackbar.js
  package/layout/PageContainer.js
Labels: enhancement

#158 fix: :bug: remove auth related styles from CoreClasses
  package/styles/CoreClasses.js
Labels: bug
