Repository wrappid/core, pull requests merged in 2024-08, with the labels that each got.

#273 fix(core): :bug: core component CoreMultiTimeRangePicker
  package/components/inputs/CoreMultiTimeRangePicker.js
Labels: bugfix

#275 docs(core): :memo: update readme
  README.md
Labels: documentation

#278 fix(core): :bug: there is error that is showing in guide modules in CoreList that has been solved
  package/components/dataDisplay/CoreListSubheader.js
Labels: bugfix

#281 feat(core): :sparkles: adding new props listType
  package/components/dataDisplay/CoreList.js
Labels: enhancement

#285 feat(core): :sparkles: adding new props and varient
  package/components/dataDisplay/CoreList.js
Labels: enhancement, requirement-proposed

#287 feat(core): :sparkles: alt props text CoreImage
  package/components/dataDisplay/CoreImage.js
Labels: enhancement

#294 fix(core): :bug: corelistitemtext validprops is named as invalidprops
  package/components/dataDisplay/CoreListItemText.js
Labels: bugfix

#296 fix(core): :bug: corelistitemsecondaryaction is implemented
  package/components/dataDisplay/CoreListItemSecondaryAction.js
  package/index.js
Labels: bugfix

#299 fix(core): :ambulance: fix CoreBackdrop valid props
  package/components/feedback/CoreBackdrop.js
Labels: bug, enhancement

#292 feat(global): :sparkles: add CoreAwayListner
  package/components/CoreAwayListner.js
  package/index.js
Labels: enhancement

#301 feat(core): :sparkles: structure change CoreTooltip
  package/components/dataDisplay/CoreTooltip.js
Labels: enhancement

#303 feat(global): :sparkles: structure change CoreCircularProgress
  package/components/feedback/CoreCircularProgress.js
Labels: enhancement

#306 feat(core): :art: name added to CoreAvatar component
  package/components/dataDisplay/CoreAvatar.js
Labels: enhancement

#307 bugfix: name to displayName
  package/components/dataDisplay/CoreAvatar.js
Labels: enhancement

#309 feat(core): ⚡ new utility function and component added
  package/components/utils/ClipboardCopyButton.js
  package/index.js
  package/utils/appUtils.js
Labels: enhancement

#310 refactor(global): :sparkles: restructure CoreDialog
  package/components/feedback/CoreDialog.js
Labels: enhancement

#312 feat(global): :sparkles: structure change in CoreBadge
  package/components/dataDisplay/CoreBadge.js
Labels: enhancement

#314 bufix: StatusText component
  package/components/dataDisplay/StatusText.js
Labels: bugfix

#317 fix(utils): :bug: add valid props and error handling
  package/components/dataDisplay/CoreTimer.js
Labels: bugfix

#319 fix(core): :bug: inputs/CoreInput pass all props
  package/components/inputs/CoreInput.js
Labels: bugfix

#322 bugfix(core): :bug: pass all props
  package/components/feedback/CoreSkeleton.js
Labels: bugfix

#320 fix(core): :bug: apk build related issue
  package/CoreRoutes.js
  package/components/dataDisplay/CoreIcon.js
  package/components/dataDisplay/dataTable/CoreDataTableBody.js
  package/components/dataDisplay/dataTable/CoreDataTableRow.js
  package/components/inputs/CoreInput.js
  package/layout/CoreLayoutItem.js
  package/layout/CoreLayoutPlaceholder.js
  package/layout/LayoutManager.js
  package/utils/componentDefaultValidations.js
Labels: bugfix

#324 fix(global): :bug: fix validProps of CoreCheckbox
  package/components/inputs/CoreCheckbox.js
Labels: bug

#326 fix(global): :sparkles: in CoreIcon restProps sent to NativeIcon
  package/components/dataDisplay/CoreIcon.js
Labels: enhancement

#331 feat(core): :sparkles: dataDisplay/CoreChip support for href and target
  package/components/dataDisplay/CoreChip.js
Labels: enhancement, frontend

#334 fix(global): :bug: fix CoreBackDrop validProps
  package/components/feedback/CoreBackdrop.js
Labels: bugfix
