Repository wrappid/core, pull requests merged in 2024-01, with the labels that each got.

#77 Create LICENSE
  LICENSE
Labels: documentation

#81 docs: :memo: generate and add ATTRIBUTION file in core
  ATTRIBUTIONS.md
  attributions.json
  package.json
  scripts/attributions.gen.js
  scripts/contribution.gen.js
Labels: documentation

#84 Update core branch from development
  ATTRIBUTIONS.md
  LICENSE
  attributions.json
  package.json
  scripts/attributions.gen.js
  scripts/contribution.gen.js
Labels: enhancement

#83 fix: :bug: correct valid props and invalid props
  package/components/feedback/CoreDialog.js
  package/components/inputs/CoreAutocomplete.js
  package/components/inputs/CoreIconButton.js
  package/components/surfaces/CoreAppBar.js
  package/components/utils/CoreModal.js
  package/components/utils/CorePopover.js
  package/components/utils/CoreProfilePopOver.js
  package/layout/WrappidGuest.layout.js
Labels: bug

#87 enhancement: Dynamic Theme Implemented
  package.json
  package/CoreApp.js
  package/components/inputs/CoreSelect.js
  package/index.js
  package/layout/WrappidGuest.layout.js
  package/package.json
  package/theme/CoreThemeProvider.js
  package/theme/ThemeSelector.js
Labels: enhancement

#90 docs(config): 📝 add missing keys in package.json
  package-lock.json
  package.json
  package/CoreApp.js
  package/layout/WrappidGuest.layout.js
  package/package-lock.json
  package/package.json
  package/theme/ThemeSelector.js
Labels: enhancement

#92 bugfix: default theme with user specific
  ATTRIBUTIONS.md
  package.json
  package/package.json
  package/store/action/appActions.js
  package/store/reducers/appReducer.js
  package/theme/CoreThemeProvider.js
  package/theme/ThemeSelector.js
Labels: bug
