Repository wrappid/core, pull requests merged in 2024-09, with the labels that each got.

#329 fix(core): :bug: corelistitem validvalues are not in array
  package/components/dataDisplay/CoreChip.js
  package/components/dataDisplay/CoreListItem.js
Labels: bugfix

#335 feat(core): :sparkles: update code of CoreLinearProgress
  package/components/feedback/CoreLinearProgress.js
Labels: enhancement

#339 bugfix: dataDisplay/CoreTable related CoreComponents prop sanitization
  package/components/dataDisplay/CoreTable.js
  package/components/dataDisplay/CoreTableBody.js
  package/components/dataDisplay/CoreTableCell.js
  package/components/dataDisplay/CoreTableContainer.js
  package/components/dataDisplay/CoreTableFooter.js
  package/components/dataDisplay/CoreTableHead.js
  package/components/dataDisplay/CoreTablePagination.js
  package/components/dataDisplay/CoreTableRow.js
  package/components/dataDisplay/CoreTableSortLabel.js
Labels: bugfix

#341 fix(global): :bug: corecontainer fixed props has been fixed
  package/components/layouts/CoreContainer.js
Labels: bugfix

#345 feat(global): :sparkles: fix CoreDateRangepicker, CoreDateTimePicker
  package/components/inputs/CoreDateRangepicker.js
  package/components/inputs/CoreDateTimePicker.js
  package/components/inputs/CoreDateTimeRangePicker.js
  package/components/inputs/CoreMultiTimeRangePicker.js
  package/components/inputs/CoreTimePicker.js
Labels: bugfix

#348 feat(core): :sparkles: add pushSnackMessage functionality in CoreSnac…
  package/index.js
  package/layout/PageContainer.js
  package/store/action/appActions.js
  package/store/reducers/appReducer.js
  package/store/types/appTypes.js
Labels: enhancement

#351 fix(core): :bug: update code in CoreAppBar
  package/components/surfaces/CoreAppBar.js
Labels: enhancement

#356 feat(global): :sparkles: remove unnecessary code from CoreSelect
  package/components/inputs/CoreSelect.js
Labels: documentation

#357 fix(core): :bug: inputs/CoreFormControl fix valid props
  package/components/inputs/CoreFormControl.js
Labels: bugfix, frontend

#359 feat(core): :sparkles: auto basic code sample creation
  package/utils/componentUtil.js
Labels: frontend

#361 feat(core): :sparkles: add validProps in CoreRating
  package/components/inputs/CoreRating.js
Labels: enhancement

#343 feat(core): :bug: add CoreDatepicker validProps
  package/components/inputs/CoreDatepicker.js
Labels: enhancement

#363 feat(global): :recycle: clean up valid props of CoreAutoComplete
  package/components/inputs/CoreAutocomplete.js
Labels: enhancement

#365 feat(core): :sparkles: update valid props of CoreCard
  package/components/surfaces/CoreCard.js
Labels: enhancement

#369 fix(core): :bugfix: navigation/CoreLink ValidProps update
  package/components/navigation/CoreLink.js
Labels: bugfix

#371 fix(global): :bug: coregrid same props are called multiple times fixed
  package/components/layouts/CoreGrid.js
Labels: bug, bugfix

#376 fix(global): :ambulance: impact handling due to app-builder models st…
  package/route/CoreRoutesProvider.js
  package/store/reducers/routeReducer.js
Labels: enhancement

#378 feat(global): :sparkles: corelist sub components comes in a grid format
  package/components/dataDisplay/CoreList.js
Labels: enhancement, requirement-proposed

#385 fix(core): :bug: theme reflection from both styles classes and theme …
  package/store/CoreProvider.js
  package/theme/CoreThemeProvider.js
Labels: bug, bugfix
