Repository wrappid/core, pull requests merged in 2024-06, with the labels that each got.

#229 fix(core): :bug: fix loading default theme
  package/theme/CoreThemeProvider.js
Labels: bugfix

#230 feat(global): :sparkles: page specfic theme suppport added
  package/layout/PageContainer.js
  package/store/reducers/themeReducer.js
  package/store/types/themeTypes.js
  package/theme/CoreThemeProvider.js
  package/theme/ThemeSelector.js
Labels: bugfix

#232 bugs & enhancement: tab fix and CoreFunctionsRegistryContext exported
  package/components/inputs/CoreAsyncSelect.js
  package/components/navigation/CoreTabHead.js
  package/index.js
Labels: bug, bugfix

#235 feat(core): :sparkles: styling tab headers for CoreCustomTabs
  package/components/navigation/CoreCustomTabs.js
Labels: enhancement

#238 feat(utils): :lipstick: change CoreImagePicker default image
  package/components/inputs/CoreImagePicker.js
Labels: frontend-web, frontend

#243 feat(core): :zap: coreOtpInput service name
  package/components/inputs/CoreOtpInput.js
Labels: frontend, api

#245 fix(core): :lipstick: component CoreAppDrawer's default menu icon alignment
  package/components/surfaces/DefaultAppBarContent.js
Labels: bugfix, frontend

#247 perf(core): :adhesive_bandage: cursor point added to see more and seeless
  package/components/dataDisplay/CoreTypographyBody1.js
  package/components/dataDisplay/CoreTypographyBody2.js
  package/components/dataDisplay/CoreTypographyCaption.js
  package/components/dataDisplay/CoreTypographyOverline.js
  package/components/dataDisplay/CoreTypographySubtitle1.js
  package/components/dataDisplay/CoreTypographySubtitle2.js
Labels: enhancement

#249 fix(global): :bug: add valid props in CoreTextarea
  package/components/inputs/CoreTextarea.js
Labels: bug

#250 fix(global): :bug: valid props add to CoreCheckbox
  package/components/inputs/CoreCheckbox.js
  package/components/inputs/forms/CoreSpecificForm.js
Labels: bug, bugfix

#252 fix(core): :bug: remove unnecessary encodingURIcomponent function
  package/components/inputs/forms/CoreSpecificForm.js
Labels: bugfix

#254 feat(global): :sparkles: update access token by refresh token
  package/components/inputs/forms/CoreForm.js
  package/components/layouts/_system/AppContainerLayout.js
  package/layout/PageContainer.js
  package/middleware/axiosInterceptor.js
  package/service/AppService.js
  package/store/action/appActions.js
  package/utils/appUtils.js
  package/utils/formUtils.js
Labels: enhancement
