Repository wrappid/core, pull requests merged in 2024-10, with the labels that each got.

#402 enhancement: toolbox component
  package/components/CoreComponentsRegistry.js
  package/components/layouts/_system/RightDrawerLayout.js
  package/components/surfaces/CoreToolBox.js
  package/index.js
  package/registry/ComponentsRegistry.js
  package/utils/componentUtil.js
Labels: enhancement

#406 fix(core): :bug: google onetap auto login off
  package/components/inputs/custom/GoogleAuthComponent.js
Labels: bugfix

#408 feat(config): :bug: fix github login api faild to call
  package/components/inputs/custom/GithubAuthComponent.js
Labels: bug, bugfix

#409 feature(core): more than 2 icon replace with 3 dot
  package/components/surfaces/CoreToolBox.js
Labels: enhancement
