Repository wrappid/core, pull requests merged in 2024-04, with the labels that each got.

#196 fix(core): :bug: Spell mistake of the validProps array in CoreListItemButton comp
  package/components/dataDisplay/CoreListItemButton.js
  package/components/inputs/CoreButton.js
Labels: bugfix

#197 refactor(core): :recycle: correct 'OnClick' to 'onClick' props
  package/components/dataDisplay/CoreEmailOrPhoneLink.js
  package/components/dataDisplay/CoreTimer.js
  package/components/dataDisplay/dataTable/CoreDataTableRow.js
  package/components/dataDisplay/dataTable/CoreDataTableToolbar.js
  package/components/dataDisplay/dataTable/CoreTableAction.js
  package/components/dataDisplay/dataTable/FilterData.js
  package/components/inputs/CoreButton.js
  package/components/inputs/CoreIconButton.js
  package/components/inputs/CoreResponsiveButton.js
  package/components/inputs/forms/CoreFieldButton.js
  package/components/inputs/forms/CoreForm.js
  package/components/inputs/forms/CoreFormHeaderActions.js
  package/components/inputs/forms/CoreFormInputs.js
  package/components/surfaces/CoreCard.js
  package/components/surfaces/CoreDrawer.js
  package/components/utils/CoreProfilePopOver.js
  package/theme/ThemeSelector.js
  package/utils/formUtils.js
Labels: enhancement

#198 enhancement: delivery oriented fix
  package/components/layouts/_system/AppContainerLayout.js
  package/components/surfaces/DefaultAppBarContent.js
  package/components/utils/CoreProfilePopOver.js
Labels: enhancement, bugfix

#199 fix(core): :bug: core appbar margin-top bug fixed
  package/styles/DefaultCoreStyles.js
  package/styles/MediumCoreStyles.js
  package/styles/SmallCoreStyles.js
Labels: bugfix

#201 feat(core): :sparkles: add defaulValidEvents props in sanatizeCompPro…
  package/utils/componentUtil.js
Labels: enhancement

#202 bugfix: deafult routes added in DefaultAppBarContent
  package/components/PageLoader.js
  package/components/surfaces/DefaultAppBarContent.js
Labels: bug

#204 enhancement: delivery oriented fixes.
  package/CoreRoutes.js
  package/components/PageLoader.js
  package/components/inputs/CoreCheckbox.js
  package/components/inputs/ParentChildMap.js
  package/config/contextHandler.js
  package/constants/constants.js
  package/route/CoreRoutesProvider.js
  package/store/reducers/routeReducer.js
  package/store/types/appTypes.js
Labels: enhancement, bugfix

#206 enhancement: theme and auth specific code handled
  package/CoreRoutes.js
  package/components/PageLoader.js
  package/components/layouts/CoreAppDiv.js
  package/components/layouts/_system/AppContainerLayout.js
  package/components/navigation/Logout.js
  package/components/navigation/SplashComponent.js
  package/components/surfaces/CoreDrawer.js
  package/components/surfaces/CoreFooter.js
  package/components/utils/CoreFade.js
  package/components/utils/CoreProfilePopOver.js
  package/components/utils/CoreTermsPrivacyLink.js
  package/development/DevelopmentInfo.js
  package/layout/PageContainer.js
  package/route/CoreRoutesProvider.js
  package/theme/CoreThemeProvider.js
Labels: enhancement
