Repository wrappid/core, pull requests merged in 2024-07, with the labels that each got.

#257 feat(global): :sparkles: page theme merge with default theme
  package/components/dataDisplay/CoreTimer.js
  package/layout/PageContainer.js
  package/store/reducers/themeReducer.js
  package/theme/CoreThemeProvider.js
  package/utils/jsonUtils.js
Labels: enhancement

#259 fix(core): :bug: coreForm data driven from props in CoreDataTableDeta…
  package/components/dataDisplay/dataTable/CoreDataTable.js
  package/components/dataDisplay/dataTable/CoreDataTableDetailsPane.js
Labels: bugfix

#262 bugfix: DataDisplay components enhancement
  package/components/dataDisplay/CoreEmailOrPhoneLink.js
  package/components/dataDisplay/CorePhoneLink.js
  package/components/layouts/CoreSection.js
Labels: bugfix

#263 fix(core): :bug: core json input changed to core json editor
  package/utils/componentMap.js
Labels: bugfix

#265 docs(global): :memo: adding pull_request_template
  .github/pull_request_template.md
Labels: documentation

#267 fix(core): :bug: coreForm read api not working with local formJson
  package/components/inputs/forms/CoreForm.js
Labels: bug, bugfix
